name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.TOKEN }}
        pr-message: "We appreciate you creating your first pull requests 🚀 Hope you're enjoying Hack4Bengal 🌟 "
